services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123.
      MYSQL_DATABASE: proba
      MYSQL_USER: usuario
      MYSQL_PASSWORD: abc123.
    ports:
     - 9906:3306
    volumes:
      - dbdata:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: usuario
      WORDPRESS_DB_PASSWORD: abc123.
      WORDPRESS_DB_NAME: proba
    volumes:
      - "./www/:/var/www/html"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  dbdata: {}
